- hosts: target_servers
  become: yes
  become_method: sudo
  tasks:
  - name: General packages are installed
    yum: name={{ item }} state=installed
    with_items:
     - vim-enhanced
     - wget
     - unzip
    tags: General_Packages

